### ISSUE TITLE
CDW: Bucket name could be parameterized

### ISSUE THREAD

**Issue by kuldeepsahu1105** [mmehra12/HOLWorkshops#11]
<img width="1009" alt="image" src="https://github.com/user-attachments/assets/8aac0269-4a63-4f66-b3b6-a1d8e2e41e8e">
Bucket name could be parameterized as similar to what has been done for user_id (later path could be hardcoded to the location we copied the csv files), so user can just copy and paste the queries directly and run seamlessly and also the hardcoding of bucket name could be removed from the document.

**Comment by mmehra12** [comment]
Fixed.

Commit : https://github.com/mmehra12/HOLWorkshops/commit/b5e964abf39b948ad1edec3183086588c1b3f7c9
